### ISSUE TITLE
Нет открывющего тега php, излишне усложнена логика. нет обьектов. Не правильное форматирование в коде( смотреть psr-1)

### ISSUE THREAD

**Issue by paladinbbk** [Cholaria23/task1#1]
https://github.com/Cholaria23/task1/blob/e5d88c70aa025f46531e7b4e652067fdcf210b68/class_Array_Even.php#L1

**Comment by Cholaria23** [comment]
Исправил class_Array_Even

**Comment by Cholaria23** [comment]
Исправил class_Array_Repl
