### ISSUE TITLE
Отступы во всех Файлах поправь!!!

### ISSUE THREAD

**Issue by paladinbbk** [Cholaria23/task1#3]
https://github.com/Cholaria23/task1/blob/60a4c2a76afa91ff0330bbe71244fff0fe333ab2/class_Array_Even.php#L6

**Comment by Cholaria23** [comment]
Правлю отступы в файлах, на предпросмотре они не меняются, а когда открываеш сам файл то отступы в норме!не могу понять почему так!

**Comment by paladinbbk** [comment]
можно просто в редакторе настроить автоформатирование.
